language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get -y install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
      script:
        - mkdir build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - make
