language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get -y install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
      script:
        - mkdir build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - make
    - os: linux
      dist: focal
      env:
        - BUILD_NAME=xbox
      compiler: gcc
      before_install:
        - sudo apt-get -y install flex bison
      script:
        - mkdir build
        - git clone --recursive https://github.com/XboxDev/nxdk.git build/nxdk
        - PATH=$PATH:/usr/lib/llvm-10/bin
        - make -f Makefile.xbox NXDK_DIR=build/nxdk
    - os: osx
      compiler: clang
      osx_image: xcode12
      addons:
        homebrew:
          packages:
            - sdl2
            - sdl2_image
            - sdl2_ttf
      script:
        - mkdir build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - make
