#ifndef RR_ASSETS_H
#define RR_ASSETS_H

typedef enum {
    RR_SPRITESHEET_INDEX_BLOCK,
    RR_SPRITESHEET_INDEX_WALL,
    RR_SPRITESHEET_INDEX_MOUSE,
    RR_SPRITESHEET_INDEX_CAT,
    RR_SPRITESHEET_INDEX_CAT_WAIT,
    RR_SPRITESHEET_INDEX_CHEESE,
    RR_SPRITESHEET_INDEX_REMAINING_LIFE,
    RR_SPRITESHEET_INDEX_CLOCK,
    RR_SPRITESHEET_INDEX_HOLE,
    RR_SPRITESHEET_INDEX_STUCK_PLAYER,
    RR_SPRITESHEET_INDEX_MOUSETRAP,

    RR_SPRITESHEET_INDEX_PLAYER_DEATH1,
    RR_SPRITESHEET_INDEX_PLAYER_DEATH2,
    RR_SPRITESHEET_INDEX_PLAYER_DEATH3,
    RR_SPRITESHEET_INDEX_PLAYER_DEATH4,
    RR_SPRITESHEET_INDEX_PLAYER_DEATH5,

    RR_SPRITESHEET_INDEX_COUNT
} rrSpriteSheetIndex;

typedef enum {
    RR_SPRITE_TITLE_LOGO,
    RR_SPRITE_SPRITESHEET,
    RR_SPRITE_COUNT
} rrSpriteIndex;

#endif
