#ifndef RR_SPRITES_H
#define RR_SPRITES_H

typedef enum {
    RR_SPRITE_BLOCK,
    RR_SPRITE_WALL,
    RR_SPRITE_MOUSE,
    RR_SPRITE_CAT,
    RR_SPRITE_CAT_WAIT,
    RR_SPRITE_CHEESE,
    RR_SPRITE_REMAINING_LIFE,
    RR_SPRITE_CLOCK,
    RR_SPRITE_HOLE,
    RR_SPRITE_STUCK_PLAYER,
    RR_SPRITE_MOUSETRAP,

    RR_SPRITE_PLAYER_DEATH1,
    RR_SPRITE_PLAYER_DEATH2,
    RR_SPRITE_PLAYER_DEATH3,
    RR_SPRITE_PLAYER_DEATH4,
    RR_SPRITE_PLAYER_DEATH5,

    RR_SPRITE_COUNT
} SpriteIndex;

#endif
